-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 08:36:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema payment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payment` DEFAULT CHARACTER SET utf8 ;
USE `payment` ;

-- -----------------------------------------------------
-- Table `payment`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment`.`user` (
  `EMAIL` VARCHAR(100) NOT NULL,
  `NOM` VARCHAR(100) NULL,
  `PRENOM` VARCHAR(100) NULL,
  `USERPASSWORD` VARCHAR(45) NOT NULL,
  `PHOTO` LONGBLOB NULL,
  `TEL` VARCHAR(45) NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment`.`compte` (
  `IDCOMPTE` INT NOT NULL,
  `NUMCOMPTE` VARCHAR(100) NOT NULL,
  `user_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IDCOMPTE`, `user_EMAIL`),
  INDEX `fk_compte_user_idx` (`user_EMAIL` ASC) VISIBLE,
  CONSTRAINT `fk_compte_user`
    FOREIGN KEY (`user_EMAIL`)
    REFERENCES `payment`.`user` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment`.`transaction` (
  `compte_IDCOMPTE` INT NOT NULL,
  `compte_user_EMAIL` VARCHAR(100) NOT NULL,
  `compte_IDCOMPTE1` INT NOT NULL,
  `compte_user_EMAIL1` VARCHAR(100) NOT NULL,
  `DATE` DATE NOT NULL,
  `HEURE` TIME NOT NULL,
  `TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`compte_IDCOMPTE`, `compte_IDCOMPTE1`, `compte_user_EMAIL`, `compte_user_EMAIL1`),
  INDEX `fk_compte_has_compte_compte4_idx` (`compte_IDCOMPTE1` ASC, `compte_user_EMAIL1` ASC) VISIBLE,
  INDEX `fk_compte_has_compte_compte3_idx` (`compte_IDCOMPTE` ASC, `compte_user_EMAIL` ASC) VISIBLE,
  CONSTRAINT `fk_compte_has_compte_compte3`
    FOREIGN KEY (`compte_IDCOMPTE` , `compte_user_EMAIL`)
    REFERENCES `payment`.`compte` (`IDCOMPTE` , `user_EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compte_has_compte_compte4`
    FOREIGN KEY (`compte_IDCOMPTE1` , `compte_user_EMAIL1`)
    REFERENCES `payment`.`compte` (`IDCOMPTE` , `user_EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
